POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Video 1 description",
    "duration": 100
}

###

GET http://localhost:3333/videos

###
GET http://localhost:3333/videos?search=node

###
PUT http://localhost:3333/videos/a249663e-f4df-40de-bfcc-da7290e0dc45
Content-Type: application/json

{
    "title": "Video 2",
    "description": "Video 1 description",
    "duration": 100
}

###
DELETE http://localhost:3333/videos/a249663e-f4df-40de-bfcc-da7290e0dc45